[build.environment]
  NETLIFY_USE_PNPM = "true"
  NODE_VERSION = "18"

[build]
  command = "OUTPUT=netlify astro build"
  publish = "dist"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
[[redirects]]
  from = "https://gpt114.chatxyz.online/*"
  to = "https://gpt112.chatxyz.online"
  force = true
